name: Rust

on:
  push:
    branches: [ "main", "jds/*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format Check
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Install targets
      run: rustup target add thumbv7em-none-eabihf && rustup target add thumbv6m-none-eabi
    - name: Test
      run: cargo test
    - name: Build (x86_64)
      run: cargo build --verbose
    - name: Build (thumbv7em-none-eabihf)
      run: cargo build --target thumbv7em-none-eabihf --verbose
    - name: Build (thumbv6m-none-eabi)
      run: cargo build --target thumbv6m-none-eabi --verbose